### ISSUE TITLE
error in binary nexus

### ISSUE THREAD

**Issue by PRASADLIFE** [edgardomortiz/vcf2phylip#1]
To convert the vcf into binary nexus it throw the error:-

Traceback (most recent call last):
  File "vcf2phylip.py", line 384, in <module>
    main()
  File "vcf2phylip.py", line 224, in main
    binsite_tmp = ''.join([(gen_bin[broken[i][0:3]]) for i in range(9, index_last_sample)])
KeyError: '1|1'

**Comment by edgardomortiz** [comment]
I will need more info, what was your command? how did you generate your vcf? could you send the first. 5000 lines of your vcf to replicate the error?

**Comment by PRASADLIFE** [comment]
This is my command to get the binary nexus format.
 #python vcf2phylip.py -i 9983.vcf --phylip-disable -n --nexus-binary
I successfully converted the vcf to nexus but to convert into binary nexus it through the error. I attached the sample file.
[first_5000.vcf.gz](https://github.com/edgardomortiz/vcf2phylip/files/1997668/first_5000.vcf.gz)

**Comment by edgardomortiz** [comment]
Thanks for reporting the bug, please test and if it works I will mark it as solved.

**Comment by PRASADLIFE** [comment]
Yes, now it's running. Thank You very much for the quick response.

**Comment by edgardomortiz** [comment]
Cool, no problem.
