### ISSUE TITLE
all SNPs were removed when converting my vcf file by using vcf2phylip

### ISSUE THREAD

**Issue by hellozo** [edgardomortiz/vcf2phylip#10]
Hello,

I found that all my SNPs were removed after converting my vcf file. I did that on the Linux system, the command I type is "python vcf2phylip.py -m 0 -fi  1111.filter.vcf".  
And the result is 
"Number of samples in VCF: 8
Total of genotypes processed: 130883
**Genotypes excluded because they exceeded the amount of missing data allowed: 130883**
Genotypes that passed missing data filter but were excluded for not being SNPs: 0
SNPs that passed the filters: 0"

I don't know why all my SNPs were removed, and how can I fix that problem?

Appreciate for your help! ^_^

**Comment by edgardomortiz** [comment]
Hi,
I just ran a test with one of my files:
`vcf2phylip.py -i file.vcf -m 0`
And ran without errors, which tells me that there must be something in your vcf that is not standard. Would you mind sending a few thousand lines to find out the problem?

**Comment by hellozo** [comment]
Hi Edgardo,



I have run a total of 12 files (they all generated by the same pipeline),
but only this file has that problem. I put my file in the attachment.
Really appreciate for your help.


 17030.filter.vcf
<https://drive.google.com/file/d/1h9vvenCxbJT_pUXVBjj_V3reWWI1Qr0u/view?usp=drive_web>

Regards,

Zoey


Edgardo M. Ortiz <notifications@github.com>

**Comment by hellozo** [comment]
> Hi,
> I just ran a test with one of my files:
> vcf2phylip.py -i file.vcf -m 0
> And ran without errors, which tells me that there must be something in your vcf that is not standard. Would you mind emailing me a few thousand lines to find out the problem?

Hi Edgardo,
I have emailed my file to you. Really appreciate for your help.

**Comment by edgardomortiz** [comment]
Hi Zoey,

Thanks for finding this bug, it was not a problem with your file but with my code. Please re-clone the repository and try again, it should be fixed. Also, just to be sure, repeat a few of your other files to verify you get the same results as before.

Edgardo

**Comment by hellozo** [comment]
> Hi Zoey,
> 
> Thanks for finding this bug, it was not a problem with your file but with my code. Please re-clone the repository and try again, it should be fixed. Also, just to be sure, repeat a few of your other files to verify you get the same results as before.
> 
> Edgardo

Hi Edgardo,

Thanks for your help. It works now. I have tried other files and they showed the same result as before. ^_^
Zoey
