### ISSUE TITLE
Key Error '-'

### ISSUE THREAD

**Issue by mwpil** [edgardomortiz/vcf2phylip#11]
Hello, 

I'm trying to convert my vcf file to phylip, but I can't work out the error I get. 

> $ python vcf2phylip.py -i cfaplusoutD.recode.vcf -o AN02:C6G73ANXX:7:250444719
> 
> Converting file cfaplusoutD.recode.vcf:
> 
> Number of samples in VCF: 47
> Traceback (most recent call last):
>   File "vcf2phylip.py", line 421, in <module>
>     main()
>   File "vcf2phylip.py", line 241, in main
>     site_tmp = ''.join([amb[''.join(sorted(set([nuc[broken[i][j]] for j in gt_idx])))] for i in range(9, index_last_sample)])
> KeyError: '-'

I'm attaching the first 2000 variants of the file
[here](https://github.com/edgardomortiz/vcf2phylip/files/3292182/all_variants_2000.vcf.zip), in case there is any way you can help. 
Thank you very much for your time, in advance.

**Comment by edgardomortiz** [comment]
Hi,
The error was caused by the SNPs whose reference allele was a gap "-", please clone again and let me know if it works. Just out of curiosity, what pipeline produced this VCF?

Edgardo

**Comment by mwpil** [comment]
It worked. This is GBS data, ran through a TASSEL pipeline with a reference genome. 
Thank you very much for your help. 
Maria.

**Comment by edgardomortiz** [comment]
Excellent, glad to help
