### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by maernster** [edgardomortiz/vcf2phylip#13]
Hi I am trying to convert a multisample vcffile to binary nexus format for SNAPP. 

I am getting following error:

Traceback (most recent call last):
  File "vcf2phylip.py", line 419, in <module>
    main()
  File "vcf2phylip.py", line 239, in main
    site_tmp = ''.join([amb[''.join(sorted(set([nuc[broken[i][j]] for j in gt_idx])))] for i in range(9, index_last_sample)])
IndexError: string index out of range

This is the command I am using:
python vcf2phylip.py -i /path/to/vcf -n

[ori_5000.vcf.gz](https://github.com/edgardomortiz/vcf2phylip/files/3443223/ori_5000.vcf.gz)

Thanks a lot in advance!

**Comment by edgardomortiz** [comment]
Hello,

I am unable to reproduce the error with the file you sent. Perhaps there is an formatting error further down in your VCF? This may indicate an incomplete VCF file for example.

Edgardo

**Comment by edgardomortiz** [comment]
By the way, the option to get the binary nexus files is `-b`, `-n` gives you a regular nexus with nucleotides.

**Comment by maernster** [comment]
Hi Edgardo, thanks for the quick reply. Yes right. I tried different options to see if I get the same error. I’ll double check my vcffile and let you know!

**Comment by maernster** [comment]
Hi Edgardo, you are right the file I sent worked. The original file passes the vcf-validator and it seems to be complete. However, there are many variants that give me an error further down. I have gone through my vcffile and identified some of the variants that give an error by subsetting the original vcf and running your script. 

These are some of the variants that give me the following error message:

Traceback (most recent call last):
  File "vcf2phylip.py", line 424, in <module>
    main()
  File "vcf2phylip.py", line 244, in main
    site_tmp = ''.join([amb[''.join(sorted(set([nuc[broken[i][j]] for j in gt_idx])))] for i in range(9, index_last_sample)])
  File "vcf2phylip.py", line 244, in <listcomp>
    site_tmp = ''.join([amb[''.join(sorted(set([nuc[broken[i][j]] for j in gt_idx])))] for i in range(9, index_last_sample)])
  File "vcf2phylip.py", line 244, in <listcomp>
    site_tmp = ''.join([amb[''.join(sorted(set([nuc[broken[i][j]] for j in gt_idx])))] for i in range(9, index_last_sample)])
IndexError: string index out of range

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	indivA	indivB	indivC	indivD	indivE	indivF	indivG	indivH	indivI	indivJ	indivL	indivM	indivN
91	8869251	.	G	T	877.39	PASS	AC=20;AN=20	GT:DP:RO:QR:AO:QA:GL	1/1:16:0:0:16:640:-57.9373,-4.81648,0	1/1:16:0:0:16:640:-57.9373,-4.81648,0	./.:.:.:.:.:.:.	1/1:14:0:0:14:560:-50.7451,-4.21442,0	./.:.:.:.:.:.:.	1/1:14:0:0:14:545:-49.3882,-4.21442,0	1/1:25:0:0:25:1000:-90.3023,-7.52575,0	1/1:17:0:0:17:674:-60.9938,-5.11751,0	1/1:14:0:0:14:560:-50.7451,-4.21442,0	1/1:22:0:0:22:877:-79.2446,-6.62266,0	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	1/1:19:0:0:19:757:-68.456,-5.71957,0	1/1:21:0:0:21:831:-75.1095,-6.32163,0
68	13351456	.	T	A	793.25	PASS	AC=22;AN=22	GT:DP:RO:QR:AO:QA:GL	1/1:21:0:0:21:840:-75.9065,-6.32163,0	1/1:15:0:0:15:594:-53.8002,-4.51545,0	./.:.:.:.:.:.:.	1/1:12:0:0:11:440:-39.5033,-3.31133,0	1/1:17:0:0:17:680:-61.5335,-5.11751,0	1/1:12:0:0:12:471:-42.7413,-3.61236,0 1/1:23:0:0:23:911:-82.302,-6.92369,0	1/1:18:0:0:18:717:-64.8598,-5.41854,0	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	1/1:20:0:0:20:800:-72.3218,-6.0206,0	1/1:23:0:0:23:915:-82.657,-6.92369,0	1/1:11:0:0:11:440:-39.9568,-3.31133,0	1/1:12:0:0:12:477:-43.2801,-3.61236,0
91	10588310	.	A	G	715.84	PASS	AC=4;AN=4	GT:DP:RO:QR:AO:QA:GL	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	1/1:14:0:0:14:560:-50.6913,-4.21442,0	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	./.:.:.:.:.:.:.	1/1:21:0:0:21:831:-75.1095,-6.32163,0	./.:.:.:.:.:.:.

Any idea why?

**Comment by edgardomortiz** [comment]
For some reason you have 14 genotypes and 13 sample names, is that correct?

**Comment by maernster** [comment]
nope, the sample names are actually 14, sorry I just deleted indivK by mistake when I copy pasted...

**Comment by edgardomortiz** [comment]
OK, I got it. The program you used to generate the VCF sometimes divides two consecutive genotypes with a space while it should always be a tab according to the description of the standard https://samtools.github.io/hts-specs/VCFv4.1.pdf
 See for example in the first row, these two genotype are separated by a space and not by a tab:
`1/1:16:0:0:16:640:-57.9373,-4.81648,0 ./.:.:.:.:.:.:.`
I guess you could you `sed` to replace all spaces by tabs. Alternatively I could make the script to split each row at any white space, but I am afraid of breaking other parts of the code (especially considering the standard specifies tabs as separators).

**Comment by edgardomortiz** [comment]
Looking at the history of your commands, it seems you used `bcftools` to merge some VCFs. Perhaps you can run `vcftools` with the option `--recode --recode-INFO-all` to ensure a correct VCF format. I say this because `freebayes` never gave me this error.

**Comment by maernster** [comment]
I tried both replacing all spaces by tabs and running vcftools recode as you said and it didn't help...
My workflow consists of:
1. variant calling with freebayes
2 .first filtering step using vcffilter
3. second filtering step using vcftools
4. merging with bcftools merge

I tried running vcf2phylip.py after each step and realized that the conversion works until step 3 where I apply the following command:
vcftools --vcf pathtovcf --recode-INFO-all --thin 5 --max-alleles 3 --out prefix

**Comment by edgardomortiz** [comment]
Hi again,
It would be better to analyze a multisample VCF, but anyway I tried and found this line:
`35	499170	.	A	T	310.326	PASS	AC=1;AF=0.5;LEN=1;TYPE=snp;ALLELICPRIMITIVE	GT	1`
Which has a haploid call, while the rest in the file were diploid, this mixture breaks the script that assumes the entire VCF has a single ploidy, once I comment that line the script finishes without errors. I can fix it, but were you expecting this in your genotypes?

**Comment by maernster** [comment]
yes, I saw that before too. Vcf-tools rewrites genotypes such as 1|. into 1. 
Vcftools turns: 
35      499170  .       A       T       310.326 PASS    AC=1;AF=0.5;LEN=1;TYPE=snp;ALLELICPRIMITIVE     GT      1|.
into:
35      499170  .       A       T       310.326 PASS    .       GT      1

**Comment by edgardomortiz** [comment]
I see, does that mean heterozygote A with a deletion? In that case the consensus would ignore the deletion. I guess you could use `sed` to replace all 0/. 1/. 0|. 1|. to homozygous for 0 or 1 respectively, or ask the `vcftools` developers if that is a bug or a feature? maybe also check you are using the most recent `vcftools`?

**Comment by maernster** [comment]
Hi Edgardo, 

I decided to delete the variants that contain 0/. 1/. 0|. 1|. because these are variants where one of the alleles that had been called by freebayes was filtered out in subsequent filtering steps. Now the conversion works! Thanks a lot for your patience and help :)

**Comment by edgardomortiz** [comment]
No problem! glad to help
