### ISSUE TITLE
genotypes excluded even if missing data is less than -m 4

### ISSUE THREAD

**Issue by a2g1n** [edgardomortiz/vcf2phylip#14]
Hi
I have a multi-sample vcf which I have filtered to retain reference and SNP calls ONLY if at least 25 samples out of 31 total samples have non-missing data. However, when I convert that into phylip using your script, genotypes are still being excluded when they should not be. Or am I understanding the -m parameter wrong? I also tried -m 0 and still facing the same problem.
Is there any way to see the excluded genotypes to troubleshoot this?

`vcf2phylip.py -i  RMPs.vcf -m 4`
Total of genotypes processed: 6372167
Genotypes excluded because they exceeded the amount of missing data allowed: 875118
Genotypes that passed missing data filter but were excluded for not being SNPs: 0
SNPs that passed the filters: 5497049
`vcf2phylip.py -i  RMPs.vcf -m 0`
Total of genotypes processed: 6372167
Genotypes excluded because they exceeded the amount of missing data allowed: 810339
Genotypes that passed missing data filter but were excluded for not being SNPs: 0
SNPs that passed the filters: 5561828

Thanks.

**Comment by edgardomortiz** [comment]
Hello,
My guess is that those excluded are deletions. If possible email me a few thousand lines (~10K) of your VCF to be sure or to fix the issue.

Edgardo

**Comment by a2g1n** [comment]
Hi Edgardo
Thanks for your mail. I had filtered my variants just for SNPs, so I doubt its deletions. Anyway I have attached part of the vcf. Thanks!
Also is it possible to get the vcf lines that the script excluded (or included)? It would be helpful for downstream analysis. For example, I would like to tell how many genes are covered in the RaxML phylogeny tree. But I can’t estimate it without knowing which vcf lines were included.

Regards
Abhinay

**Comment by edgardomortiz** [comment]
Hi again, I don't see any attachment...

**Comment by a2g1n** [comment]
Now?
[test.vcf.gz](https://github.com/edgardomortiz/vcf2phylip/files/3747736/test.vcf.gz)

**Comment by a2g1n** [comment]
Hi again @edgardomortiz 
I just tried with a nonsensical value of -m -1000 and it does not filter out any SNPs. So it is definitely dependent on -m I think?

**Comment by ke-crawford** [comment]
I had this problem too and it was solved by including a nonsensical value of -m.

A side question: is it possible to get it to include MNPs? I'd like to keep these in my fasta.

**Comment by edgardomortiz** [comment]
> Hi again @edgardomortiz
> I just tried with a nonsensical value of -m -1000 and it does not filter out any SNPs. So it is definitely dependent on -m I think?

Hi, I think I fixed the bug, thanks for finding it. Could you re-clone the repository and re-run the script on your files to see if it behaves correctly now?

Edgardo

**Comment by edgardomortiz** [comment]
> I had this problem too and it was solved by including a nonsensical value of -m.
> 
> A side question: is it possible to get it to include MNPs? I'd like to keep these in my fasta.

The problem with MNPs is that even though they are usually the same length across samples (when you can assume that they are aligned) there are also cases where they come unaligned or have different lengths (for example I saw that many times coming from freebayes). The solution in this case I to normalize allele variant representation with something like `vcfallelicprimitives`, check here: https://github.com/ekg/freebayes#normalizing-variant-representation

Edgardo
