### ISSUE TITLE
Is there a way to get vcf2phylip to output the REF for non-variant positions rather than N?

### ISSUE THREAD

**Issue by richarddhaigh** [edgardomortiz/vcf2phylip#15]
Hi Edgardo

I have a series of large multi-vcf files of bacterial snps (so everything is haploid) that I want to convert to phylip and use ultimately with FastTree (http://www.microbesonline.org/fasttree/#FAQ). I have used vcf2phylip on some test files and it has all worked nicely and quickly however I then found that FastTree wont accept non-ACGT characters so it doesn't like the output I now have. I would really like to use FastTree (this work is a comparison against another FastTree using pipeline) so is there a way to get vcf2phylip to output the REF nucleotide rather than N in the final phylip file? 

Thanks for your help

Richard

**Comment by richarddhaigh** [comment]
Hi Edgardo

Just a quick update as I have solved the problem - in using vcf-merge to create the multi-vcf files I had inadvertently left out a "-R 0" modifier which tells the program to input reference for non-snp positions thus introducing the Ns. Now the script is working very nicely.

Thanks

**Comment by edgardomortiz** [comment]
Glad to hear, and sorry to answer so slowly, work has been intense lately. I remember FastTree would simply treat ambiguous characters as missing data, but I think that is irrelevant for your haploid case. Another quick software that can handle large matrices is IQ-TREE, I would give it a try too.

Edgardo

**Comment by richarddhaigh** [comment]
Now I have found my mistake everything is working fine. Thanks for the script it is very useful.

**Comment by tseemann** [comment]
@richarddhaigh don't use FastTree; some reviewers will reject your paper (somewhat fairly). I suggest `iqtree` and `-fast` option while exploring.

**Comment by richarddhaigh** [comment]
@tseemann  I know there was a problem with FastTree a while ago - I thought that was solved? I am still getting some ambiguity with FastTree with my TB samples as the fine detail on my snp derived trees doesn't quite match what I know from large deletions so I will have a look at iqtree. 
Thanks

**Comment by tseemann** [comment]
@richarddhaigh you are probably referring to this blog post by my good colleage @koadman
https://microbe.net/2015/03/25/important-read-from-aaron-darling-not-so-fast-fasttree/

Sure, that fixes one problem. But FastTree is really taking _lots_ of shortcuts and has given wrong trees for some of my colleagues.  Computers are fast enough now, and esp with M.tb you have so few SNPs, you can easily afford to use a more thorough tree search.
