### ISSUE TITLE
Plans to port to python3 ?

### ISSUE THREAD

**Issue by tseemann** [edgardomortiz/vcf2phylip#16]
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
 Please upgrade your Python as Python 2.7 won't be maintained after that date. 
A future version of pip will drop support for Python 2.7. 
More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

**Comment by edgardomortiz** [comment]
Hello, I think it can run under python3 without problem, but I will make the "official" changes soon.

Edgardo

**Comment by danielecook** [comment]
@edgardomortiz https://github.com/edgardomortiz/vcf2phylip/pull/18

**Comment by tseemann** [comment]
@edgardomortiz @danielecook one final change needed -> https://github.com/edgardomortiz/vcf2phylip/pull/20

**Comment by tseemann** [comment]
1. :check: 
2. :check:

**Comment by sjackman** [comment]
I've opened PR https://github.com/brewsci/homebrew-bio/pull/997
