### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by joswald** [edgardomortiz/vcf2phylip#19]
Hi - Is this a Python 3 issue? 
(base) Jessicas-MacBook-Pro-2:Monadenia_filtered_SNPs jessicaoswald$ python vcf2phylip.py -i DP3g95maf05.recode.vcf 
Traceback (most recent call last):
  File "vcf2phylip.py", line 431, in <module>
    main()
  File "vcf2phylip.py", line 123, in main
    line = line.decode("UTF-8")
AttributeError: 'str' object has no attribute 'decode'

Thanks, 
Jess

**Comment by edgardomortiz** [comment]
Hello,

Yes, I merged changes made by someone else and didn't test, my bad. I just removed the line, tested and it works. Please reclone, does it work for you as well?

Edgardo

**Comment by joswald** [comment]
Hi Edgardo, Thanks for the quick reply. I get this still: 
(base) Jessicas-MacBook-Pro-2:Monadenia_filtered_SNPs jessicaoswald$ python vcf2phylip.py -i DP3g95maf05.recode.vcf -o pop4_UF446056 -f 
Traceback (most recent call last):
  File "vcf2phylip.py", line 431, in <module>
    main()
  File "vcf2phylip.py", line 123, in main
    line = line.decode("UTF-8")
AttributeError: 'str' object has no attribute 'decode'

** I am running the script on a HPC with python2 and the old script works. However, can you provide information regarding the criteria used to filter the SNP data? i.e Why is the majority of the data getting removed in the below situation? 

Number of samples in VCF: 112
Total of genotypes processed: 902
Genotypes excluded because they exceeded the amount of missing data allowed: 0
Genotypes that passed missing data filter but were excluded for not being SNPs: 571
SNPs that passed the filters: 331

Thanks, 
 Jessica

**Comment by edgardomortiz** [comment]
I have just checked the script and there isn't any `.decode()` function anymore. Please redownload or reclone the repository to ensure you have the latest update. The script should work with either python2 or 3. Please let me know if it works.

Edgardo

**Comment by edgardomortiz** [comment]
About the default filters, it will exclude any SNP that is not at least in four samples. Multinucleotide variation (non-SNPs) are also skipped because they are not aligned. If you obtained this VCF through `freebayes` you can do:
```
freebayes ... | vcfallelicprimitives -kg > calls.vcf
```
see: https://github.com/ekg/freebayes#normalizing-variant-representation

**Comment by joswald** [comment]
The script works. Thank you, Edgardo. 
Jess

**Comment by edgardomortiz** [comment]
Excellent! glad to help
