### ISSUE TITLE
alt allele assignment for heterozygous SNP site instead of IUPAC codes

### ISSUE THREAD

**Issue by kumarsaurabh20** [edgardomortiz/vcf2phylip#23]
Hi,

is it possible with the current script to assign alternate allele for all heterozygous sites, instead of IUPAC codes? With the default, while trying to translate the converted phylip file, many stop codons are appearing in the alignment because of IUPAC codes and its a painful process to correct 1-2 million SNPs. Any suggestions? I am sure it won't be difficult to add this functionality as an option.

Many thanks.

Kumar

**Comment by edgardomortiz** [comment]
That sounds feasible, however I will be able to work on it in a couple of days. I will keep you updated.

**Comment by kumarsaurabh20** [comment]
Many thanks Edgardo.

**Comment by edgardomortiz** [comment]
Hi, I was working on the code when I found an interesting case:
`REF=A`, and `ALT=C,T`, then I find some heorzygote genotypes `CT` which are both `ALT`, what behavior would you propose in that case?

**Comment by edgardomortiz** [comment]
I guess the most logical option is to randomly resolve the genotype when is not homozygous, especially when working with polyploids.

I went ahead and pushed an update with a new option `-r` or `--resolve-IUPAC` that chooses a nucleotide from a heterozygous genotype at random to avoid IUPAC ambiguities in the output matrices.

Check it out and tell me if it fits your purposes ...
