### ISSUE TITLE
Phylogenetic tree

### ISSUE THREAD

**Issue by devenderarora** [edgardomortiz/vcf2phylip#28]
Dear Sir,
Any lead how can we import .py generated  file in RAxML, IQTREE, and MrBayes? I am not able to do it successfully. Is there any example for the the same? 
Thanks 
Devender Arora

**Comment by edgardomortiz** [comment]
`vcf2phylip` only transforms VCF files into a matrix (.phy, .fasta, .nexus) than _then_ can be used in any phylogenetic inference software. I guess this is a typo, but what do you mean by importing the `.py` generated, `vcf2phylip` generates matrices with extensions `.nex`, `.fasta`, or `.phy`
For example running a PHYLIP (`.phy`) matrix of SNPs in IQ-TREE2 would be some like this:
`iqtree2 -s example.phy -st DNA -m GTR+ASC`

What commands did you try that were not working?

Edgardo

**Comment by devenderarora** [comment]
I tried iqtree -s my_file.phy and it ended up with failed composition chi2 test. The phy file look like composed of amino acid sequence do I need to add a tag -st PROTEIN?

**Comment by edgardomortiz** [comment]
But you have nucleotides, not aminoacids (am I right?), try using `-st DNA`

**Comment by devenderarora** [comment]
Yes, it is nucleotides. I crossed check and re-run the file again with -st DNA.

**Comment by splaisan** [comment]
If this can help others, I had a very similar issue coming from multiallelic calls resulting in IUPAC letters. 
I ran the vcf2phylip  command again with -r to resolve multiallelic calls to a randomly chosen base and removed non-SNP calls from my input to simplify the alignment problem.
I also required that all my samples be genotypes using -m <smpl#>
IQ tree now computes all possible model combinations but at least only reported 1 fallout sample where all failed before

**Comment by FionaMoon** [comment]
Do you mean the sequence like this?

```
$ cat Pt-12_ALL.min3.phy  | less -S
3 376745
SRR10874860   RWMRRYYYRRRSRRSKRRMRSKRYRSSKMMRRYSSYWKRRYYYRSMYYYSRRWRRRRYKSRRYSRRYRKRMRRRR
SRR10874861   RWMRRYYYRRRSRRSKRRMRSKRYRSSKMMRRYSSYWKRRYYYRSMYYYSRRWRRRRYKSRRYSRRYRKRMRRRR
SRR10874859   RWMRRYYYRRRSRRSKRRMRSKRYRSSKMMRRYSSYWKRRYYYRSMYYYSRRWRRRRYKSRRYSRRYRKRMRRRR
```
I ran gatk first for my sample then converted vcf.gz to .phy by vcf2phylip.
The result seems quite strange.
