### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hannahhalp** [edgardomortiz/vcf2phylip#3]
Hello, when I run this script in terminal I get the following error message:

'File "vcf2phylip.py", line 190
    print str(snp_num)+" genotypes processed"
            ^
SyntaxError: invalid syntax'

Thanks!
Hannah

**Comment by edgardomortiz** [comment]
Hi Hannah,

Are you using python 2?, how did you execute the command?


Edgardo

**Comment by hannahhalp** [comment]
HI Edgardo,

I was using Python 3. I reran the script using python 2 and it worked. Sorry for opening an issue when the problem was user error!

**Comment by edgardomortiz** [comment]
No problem!
