### ISSUE TITLE
Multiple VCF files?

### ISSUE THREAD

**Issue by TakashiKoyama** [edgardomortiz/vcf2phylip#30]
Hi,

I would like to create a phylip file from several VCF files produced by ATLAS variant caller.
Since ATLAS seems not to support producing gvcf files to date, I have several VCFs from different individuals.
I tried vcf2phylip.py with options like
```
vcf2phylip.py -i Ind.vcf.gz -i Ind.vcf.gz --min-samples-locus 2
```
but got an error.

Does this script support multiple inputs?
Or could you suggest any alternative ways?(Merge VCFs before the script?)

Thank you for your kind helps!

**Comment by edgardomortiz** [comment]
Hi, you need to merge your VCFs first with a program like `bcftools`:
http://samtools.github.io/bcftools/bcftools.html#merge

In this particular case I guess the error is that `min-samples` is not appropriate. It is always more useful if you provide the command as well as the error that was printed to the screen.

Edgardo

**Comment by TakashiKoyama** [comment]
Thank you for your quick reply!
I will try merging VCFs!

The code and error I got are as follows.
```
$ vcf2phylip.py -i Ind1.vcf.gz -i Ind2.vcf.gz --min-samples-locus 2
Converting file 'Ind1.vcf.gz':

Number of samples in VCF: 1
Traceback (most recent call last):
  File "/usr/local/genome/bin/vcf2phylip.py", line 444, in <module>
    main()
  File "/usr/local/genome/bin/vcf2phylip.py", line 276, in main
    site_tmp = get_matrix_column(record, num_samples, resolve_IUPAC)
  File "/usr/local/genome/bin/vcf2phylip.py", line 125, in get_matrix_column
    column += ambiguities["".join(sorted(set([nt_dict[j] for j in genotype])))]
KeyError: 'a'
```
Wrong command?

**Comment by edgardomortiz** [comment]
That is an unusual error, would you mind emailing me a few thousand lines from your VCF?

**Comment by TakashiKoyama** [comment]
I mailed you with my VCFs.

**Comment by edgardomortiz** [comment]
Please re-clone the repository, I updated the version to `2.5`, that error should not appear again. The problem was that your reference had lowercase characters.
Also the command takes _only one_ VCF file which has to be merged from multiple samples (the second `-i` is just ignored).

Please let me know if it works.

**Comment by TakashiKoyama** [comment]
It works!
Thank you so much!

**Comment by edgardomortiz** [comment]
Excellent, I'm glad it helped. I will close the issue now, feel free to re-open if necessary.

Edgardo
