### ISSUE TITLE
Give option for name and directory of output file

### ISSUE THREAD

**Issue by vmkalbskopf** [edgardomortiz/vcf2phylip#32]
I use snakemake, where one has to specify the name of the output file before hand. 

At the moment, vcftophylip creates a file in the directory of the source file and replaces the vcf suffix with 'min4.phy' when using default options.

It's very useful if I can specify the name and directory of the output file. Saves me extra commands in snakemake. It also brings your program into line with standard unix utilities.

**Comment by edgardomortiz** [comment]
You are right, I have been meaning to add the option. However in certain cases multiple files can be produced. Would it be OK if only the output folder can be specified? maybe output folder and prefix for the output files...

**Comment by vmkalbskopf** [comment]
Output folder and prefix would be great options.

**Comment by edgardomortiz** [comment]
Added to version 2.6! Thanks for the suggestion
