### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by XK4959** [edgardomortiz/vcf2phylip#33]
Hello 
I downloaded the software from this URL "wget https://github.com/edgardomortiz/vcf2phylip/archive/refs/tags/2.6.tar.gz" and used the "tar xf vcf2phylip-2.6.tar.gz" command to decompress it , And then I ran the "python vcf2phylip -h" command, and encountered the following problems:

Traceback (most recent call last):
  File "vcf2phylip.py", line 26, in <module>
    from pathlib import Path
ImportError: No module named pathlib

How can i fix it？
best wishes 
xin long

**Comment by edgardomortiz** [comment]
Hi, you need python >=3.4, unfortunately python 2 is no longer supported so I moved the script to python 3

**Comment by XK4959** [comment]
Thank you successfully solved the problem

**Comment by edgardomortiz** [comment]
great!
