### ISSUE TITLE
Invalid character * in the alignment

### ISSUE THREAD

**Issue by Rahmmy** [edgardomortiz/vcf2phylip#35]
Hello,
Thanks for this amazing script. 
I converted a 264 sample vcf file into a fasta alignment using vcf2phylip with default parameters. And attempted constructing a phylogeny using iqtree. this was unsuccessful because of the presence of invalid * characters in multiple sites in the alignment.
Any recommendations?

**Comment by edgardomortiz** [comment]
If you email me a few thousand lines from your VCF I might be able to diagnose the issue.

Edgardo

**Comment by giyany** [comment]
Hi,
I encountered the same issue with our fasta alignment. Was there any insight on the issue?

**Comment by linsson** [comment]
Same problem, iqtree doesn't like "*"

I cannot send a vcf file but this is an extract of it:

#CHROM  POS     REF     ALT     011080  011660  134660  134670
SL4.0ch01       81479   C       T       1/1:1,47:48:99:.:.:1286,116,0:. 1/1:0,10:10:30:.:.:291,30,0:.   1/1:0,50:50:99:.:.:1488,150,0:. 1/1:3,38:41:34:.:.:1070,34,0:.
SL4.0ch01       117424  A       G       1|1:2,37:39:55:1|1:117420_T_C:808,55,0:117420   1/1:0,15:15:44:.:.:315,44,0:.   1/1:4,47:51:19:.:.:986,19,0:.   1/1:2,46:48:86:.:.:1051,86,0:.
SL4.0ch01       139548  C       T,A     1/1:0,55,0:55:99:.:.:1633,165,0,1633,165,1633:. 0/1:3,15,0:18:25:.:.:356,0,25,365,69,434:.      0/0:48,0,0:48:99:.:.:0,100,1407,100,1407,1407:. 0/0:48,0,0:48:99:.:.:0,109,1252,109,1252,1252:.
SL4.0ch01       179250  G       T,*,C   1/1:1,49,0,0:50:99:.:.:1524,120,0,1527,147,1555,1527,147,1555,1555:.    1/1:0,12,0,0:12:36:.:.:357,36,0,357,36,357,357,36,357,357:.     1/1:1,49,0,0:50:99:.:.:1521,115,0,1524,146,1554,1524,146,1554,1554:. 1/1:1,51,0,0:52:99:.:.:1588,121,0,1523,151,1511,1523,151,1511,1511:.
SL4.0ch01       225060  A       G       0/0:50,0:50:99:.:.:0,120,1800:. 0/0:10,0:10:30:.:.:0,30,246:.   0/0:50,0:50:99:.:.:0,104,1487:. 0/0:50,0:50:99:.:.:0,117,1374:.
SL4.0ch01       290172  G       A       0/0:35,0:35:74:.:.:0,74,870:.   ./.:1,0:1:.:.:.:0,0,0:. 1/1:1,39:40:91:.:.:1262,91,0:.  1/1:0,32:32:96:.:.:1121,96,0:.
SL4.0ch01       323011  A       T,*     2/2:0,0,25:25:75:.:.:939,939,939,75,75,0:.      2/2:0,0,2:2:6:.:.:76,76,76,6,6,0:.      2/2:1,0,28:32:56:.:.:1081,988,972,56,92,0:.     2/2:1,0,48:49:99:.:.:1786,1789,1825,108,144,0:.

Here are 4 accessions with "*" at position 7; ALT is T,* and their GT is 2/2. I just had a quick view in the code...I am not sure, really, I guess this part

nt_dict = {str(0): record[3].replace("-","*").upper(), ".": "N"}
\# <NON_REF> must be replaced by the REF in the ALT field for GVCFs from GATK
alt = record[4].replace("-", "*").replace("<NON_REF>", `nt_dict["0"])

might have some relevance.

**Comment by edgardomortiz** [comment]
Hi @linsson ,

I requested some sample data from the original poster but got no reply. Could you send me a few thousand lines from the VCF to investigate the issue?

Edgardo

**Comment by giyany** [comment]
Hi,

Seeing that this discussion is ongoing, in the meantime I found the vcf contains a few indels, that I assumed were removed. Filtering them solved the issue as one would expect.

**Comment by edgardomortiz** [comment]
Great, good to know, would you mind pasting a couple of examples so I can parse them or skip them directly from the script?

**Comment by giyany** [comment]
Happily: you mean from the vcf file? 


Scaffold_1028   95604   .       G       A,*     7611.28 PASS    AC=49,2;AF=0.583,0.024;AN=84;BaseQRankSum=0;DP=407;ExcessHet=0;FS=0;InbreedingCoeff=0.6958;MLEAC=71,2;MLEAF=0.657,0.019;MQ=38.86;MQRankSum=1;QD=34.13;ReadPosRankSum=1;SOR=0.6
07        GT:AD:DP:FT:GQ:PGT:PID:PL:PS    1/1:0,4,1:5:PASS:12:.:.:133,12,0,133,12,133:.   1/1:0,4,2:6:PASS:12:.:.:125,12,0,125,12,125:.   ./.:2,0,0:2:genotypedepth:6:.:.:0,6,73,6,73,73:.        0/0:8,0,0:8:PASS:21:.:.:0,21,315,21,315,315:
.   ./.:2,0,0:2:genotypedepth:6:.:.:0,6,72,6,72,72:.        ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    2|2:0,0,6:6:PASS:19:1|1:95542_G_C:272,272,272,19,19,0:95542     ./.:7,0,0:7:PASS:.:.:.:0,0,0,0,0,0:.    0/0:10,0,0:10:PASS:0:.:.:0,0,107,0
,107,107:.    ./.:0,2,0:2:genotypedepth:6:.:.:49,6,0,49,6,49:.        ./.:0,3,0:3:genotypedepth:9:.:.:113,9,0,113,9,113:.     ./.:2,0,0:2:genotypedepth:6:.:.:0,6,72,6,72,72:.        ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    ./.:1,0,0:1:PASS
:.:.:.:0,0,0,0,0,0:.    1/1:0,6,0:6:PASS:18:.:.:235,18,0,235,18,235:.   1/1:0,5,0:5:PASS:15:.:.:171,15,0,171,15,171:.   1/1:0,9,0:9:PASS:27:.:.:376,27,0,376,27,376:.   ./.:1,0,0:1:PASS:.:.:.:0,0,0,0,0,0:.    ./.:0,0,0:0:PASS:.:.:.:0,0,0,0
,0,0:.    ./.:1,0,0:1:genotypedepth:3:.:.:0,3,42,3,42,42:.        ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    0/0:15,0,0:15:PASS:42:.:.:0,42,630,42,630,630:. 1/1:0,11,0:11:PASS:33:.:.:437,33,0,437,33,437:. 0/0:11,0,0:11:PASS:33:.:.:0,33,459,3
3,459,459:. 0/0:16,0,0:16:PASS:45:.:.:0,45,675,45,675,675:. 1/1:0,9,0:9:PASS:27:.:.:365,27,0,365,27,365:.   1/1:0,4,0:4:PASS:12:.:.:133,12,0,133,12,133:.   0/0:12,0,0:12:PASS:33:.:.:0,33,495,33,495,495:. 1/1:0,9,0:9:PASS:27:.:.:315,27,0,3
15,27,315:.   ./.:0,3,0:3:genotypedepth:9:.:.:125,9,0,125,9,125:.     0/0:4,0,0:4:PASS:12:.:.:0,12,141,12,141,141:.   ./.:2,0,0:2:genotypedepth:6:.:.:0,6,72,6,72,72:.        0/0:9,0,0:9:PASS:24:.:.:0,24,360,24,360,360:.   0/0:8,0,0:8:PASS
:24:.:.:0,24,232,24,232,232:.   0/0:8,0,0:8:PASS:21:.:.:0,21,315,21,315,315:.   0/0:4,0,0:4:PASS:12:.:.:0,12,121,12,121,121:.   ./.:2,0,0:2:PASS:.:.:.:0,0,0,0,0,0:.    1|1:0,9,0:9:PASS:27:1|1:95603_C_G:405,27,0,405,27,405:95603     1|1:0,
10,1:11:PASS:30:1|1:95603_C_G:450,30,0,450,30,450:95603   1/1:0,7,0:7:PASS:21:.:.:220,21,0,220,21,220:.   1/1:0,6,1:7:PASS:18:.:.:217,18,0,217,18,217:.   ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    1/1:0,13,0:13:PASS:39:.:.:539,39,0,539,39,53
9:. 1/1:0,4,0:4:PASS:12:.:.:158,12,0,158,12,158:.   1/1:0,9,0:9:PASS:26:.:.:295,26,0,295,26,295:.   1/1:0,11,0:11:PASS:33:.:.:394,33,0,394,33,394:. 1/1:0,4,2:6:PASS:12:.:.:154,12,0,154,12,154:.   1/1:0,10,0:10:PASS:30:.:.:427,30,0,427,30,
427:. 1|1:0,6,0:6:PASS:18:1|1:95603_C_G:270,18,0,270,18,270:95603     ./.:2,0,0:2:PASS:.:.:.:0,0,0,0,0,0:.    ./.:2,0,0:2:PASS:.:.:.:0,0,0,0,0,0:.    0/0:11,0,0:11:PASS:33:.:.:0,33,413,33,413,413:. ./.:2,0,0:2:genotypedepth:6:.:.:0,6,84,6
,84,84:.        0/0:8,0,0:8:PASS:24:.:.:0,24,322,24,322,322:.   0/0:16,0,0:16:PASS:48:.:.:0,48,600,48,600,600:. ./.:1,0,0:1:PASS:.:.:.:0,0,0,0,0,0:.    1/1:0,9,0:9:PASS:27:.:.:318,27,0,318,27,318:.   1/1:0,5,0:5:PASS:15:.:.:197,15,0,197,1
5,197:.   0/0:4,0,0:4:PASS:12:.:.:0,12,157,12,157,157:.   0/1:5,3,0:8:PASS:99:.:.:102,0,181,117,190,307:. 0/1:6,6,0:12:PASS:99:.:.:202,0,195,221,213,434:.        ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    ./.:2,0,0:2:genotypedepth:6:.:.:0,6,
84,6,84,84:.        1/1:0,14,0:14:PASS:42:.:.:517,42,0,517,42,517:. 0/1:2,2,0:4:PASS:54:.:.:54,0,78,60,84,144:.     ./.:2,0,0:2:genotypedepth:6:.:.:0,6,57,6,57,57:.        ./.:1,0,0:1:genotypedepth:3:.:.:0,3,42,3,42,42:.
Scaffold_1028   151063  .       T       .       .       PASS    AN=82;DP=346    GT:DP:FT:RGQ    ./.:0:PASS:0    ./.:1:genotypedepth:3   0/0:4:PASS:9    0/0:8:PASS:18   0/0:4:PASS:12   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:5:
PASS:15   0/0:8:PASS:24   ./.:0:PASS:0    ./.:3:genotypedepth:9   0/0:4:PASS:12   ./.:1:genotypedepth:3   0/0:8:PASS:24   ./.:3:genotypedepth:9   ./.:3:genotypedepth:9   0/0:4:PASS:12   0/0:4:PASS:12   0/0:8:PASS:24   0/0:5:PASS:15   ./.:
1:genotypedepth:3   0/0:6:PASS:18   0/0:12:PASS:30  ./.:12:PASS:0   0/0:10:PASS:30  0/0:11:PASS:33  ./.:2:genotypedepth:6   0/0:9:PASS:24   0/0:11:PASS:33  ./.:2:genotypedepth:6   ./.:0:PASS:0    ./.:1:genotypedepth:3   ./.:3:genotypedept
h:9   0/0:10:PASS:30  ./.:3:genotypedepth:9   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:5:PASS:15   0/0:11:PASS:33  0/0:8:PASS:24   0/0:8:PASS:24   0/0:5:PASS:15   0/0:9:PASS:27   0/0:9:PASS:21   0/0:11:PASS:30  0/0:15:PASS:42
./.:3:genotypedepth:6   0/0:4:PASS:12   0/0:11:PASS:33  ./.:0:PASS:0    ./.:1:genotypedepth:3   0/0:4:PASS:12   0/0:4:PASS:12   0/0:4:PASS:9    ./.:2:genotypedepth:6   0/0:7:PASS:21   ./.:1:genotypedepth:3   ./.:1:genotypedepth:3   0/0:4:
PASS:12   0/0:5:PASS:15   0/0:5:PASS:12   0/0:6:PASS:15   0/0:6:PASS:18   0/0:5:PASS:12   0/0:5:PASS:15   0/0:8:PASS:24   ./.:3:genotypedepth:9
Scaffold_1028   151067  .       A       .       .       PASS    AN=82;DP=356    GT:DP:FT:RGQ    ./.:0:PASS:0    ./.:1:genotypedepth:3   ./.:6:PASS:0    0/0:8:PASS:18   0/0:4:PASS:12   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:5:
PASS:12   0/0:11:PASS:30  ./.:0:PASS:0    ./.:3:genotypedepth:9   0/0:4:PASS:9    ./.:1:genotypedepth:3   0/0:8:PASS:24   ./.:3:genotypedepth:6   ./.:3:genotypedepth:9   0/0:4:PASS:12   0/0:4:PASS:12   0/0:8:PASS:24   0/0:5:PASS:15   ./.:
1:genotypedepth:3   0/0:6:PASS:18   0/0:10:PASS:27  0/0:13:PASS:36  0/0:10:PASS:30  0/0:12:PASS:33  ./.:2:genotypedepth:6   0/0:9:PASS:24   0/0:12:PASS:36  ./.:2:genotypedepth:6   ./.:0:PASS:0    ./.:1:genotypedepth:3   ./.:3:genotypedept
h:9   0/0:11:PASS:33  ./.:3:genotypedepth:9   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:6:PASS:18   0/0:11:PASS:33  0/0:8:PASS:24   0/0:8:PASS:24   0/0:5:PASS:15   0/0:9:PASS:24   0/0:7:PASS:18   0/0:11:PASS:30  0/0:14:PASS:42
./.:2:genotypedepth:6   0/0:4:PASS:12   0/0:11:PASS:33  ./.:0:PASS:0    ./.:2:genotypedepth:6   0/0:4:PASS:12   0/0:5:PASS:15   0/0:5:PASS:12   ./.:2:genotypedepth:6   0/0:7:PASS:21   ./.:1:genotypedepth:3   ./.:1:genotypedepth:3   0/0:5:
PASS:15   0/0:5:PASS:15   0/0:5:PASS:12   0/0:6:PASS:15   0/0:6:PASS:18   0/0:6:PASS:15   0/0:5:PASS:15   0/0:9:PASS:27   ./.:3:genotypedepth:9
Scaffold_1028   151068  .       A       .       .       PASS    AN=82;DP=360    GT:DP:FT:RGQ    ./.:0:PASS:0    ./.:1:genotypedepth:3   ./.:6:PASS:0    0/0:8:PASS:18   0/0:4:PASS:12   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:5:
PASS:12   0/0:11:PASS:30  ./.:0:PASS:0    ./.:3:genotypedepth:9   0/0:4:PASS:9    ./.:1:genotypedepth:3   0/0:8:PASS:24   0/0:4:PASS:9    ./.:3:genotypedepth:9   0/0:4:PASS:12   0/0:4:PASS:12   0/0:8:PASS:24   0/0:5:PASS:15   ./.:1:genoty
pedepth:3   0/0:6:PASS:18   0/0:10:PASS:27  ./.:12:PASS:0   0/0:10:PASS:30  0/0:12:PASS:33  ./.:2:genotypedepth:6   0/0:9:PASS:27   0/0:12:PASS:36  ./.:2:genotypedepth:6   ./.:0:PASS:0    ./.:1:genotypedepth:3   ./.:3:genotypedepth:9   0/
0:12:PASS:36  ./.:3:genotypedepth:9   ./.:3:genotypedepth:9   ./.:2:genotypedepth:6   0/0:6:PASS:18   0/0:11:PASS:33  0/0:8:PASS:24   0/0:8:PASS:24   0/0:5:PASS:15   0/0:9:PASS:24   0/0:7:PASS:18   0/0:11:PASS:30  0/0:14:PASS:39  ./.:2:ge
notypedepth:6   0/0:5:PASS:15   0/0:12:PASS:36  ./.:0:PASS:0    ./.:2:genotypedepth:6   0/0:4:PASS:12   0/0:5:PASS:15   0/0:5:PASS:12   ./.:2:genotypedepth:6   0/0:7:PASS:21   ./.:1:genotypedepth:3   ./.:1:genotypedepth:3   0/0:5:PASS:15
   0/0:5:PASS:15   0/0:5:PASS:12   0/0:6:PASS:15   0/0:7:PASS:21   0/0:6:PASS:15   0/0:5:PASS:15   0/0:9:PASS:27   ./.:3:genotypedepth:9
Scaffold_1028   155472  .       T       C,*     3012.69 PASS    AC=12,2;AF=0.125,0.021;AN=96;BaseQRankSum=0;DP=556;ExcessHet=0;FS=1.485;InbreedingCoeff=0.5912;MLEAC=13,3;MLEAF=0.103,0.024;MQ=31.67;MQRankSum=0;QD=30.76;ReadPosRankSum=1;SOR
=1.053    GT:AD:DP:FT:GQ:PGT:PID:PL:PS    ./.:1,0,0:1:genotypedepth:3:.:.:0,3,30,3,30,30:.        ./.:3,0,0:3:genotypedepth:9:.:.:0,9,125,9,125,125:.     1|1:0,24,0:24:PASS:72:1|1:155402_CAT_C:1080,72,0,1080,72,1080:155402    0/0:10,0,0:1
0:PASS:24:.:.:0,24,360,24,360,360:. 0/0:4,0,0:4:PASS:12:.:.:0,12,129,12,129,129:.   ./.:2,0,0:2:genotypedepth:6:.:.:0,6,84,6,84,84:.        ./.:3,0,0:3:genotypedepth:6:.:.:0,6,90,6,90,90:.        0/0:15,0,0:15:PASS:42:.:.:0,42,630,42,630,
630:. 0/0:18,0,0:18:PASS:48:.:.:0,48,720,48,720,720:. 0/0:7,0,0:7:PASS:0:.:.:0,0,209,0,209,209:.      0/0:5,0,0:5:PASS:0:.:.:0,0,42,0,42,42:. 1|1:0,9,0:9:PASS:27:1|1:155402_CAT_C:405,27,0,405,27,405:155402 ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0
,0:.    1|1:0,24,0:24:PASS:72:1|1:155402_CAT_C:1080,72,0,1080,72,1080:155402    ./.:1,0,0:1:genotypedepth:3:.:.:0,3,42,3,42,42:.        0/0:6,0,0:6:PASS:18:.:.:0,18,213,18,213,213:.   ./.:2,0,0:2:genotypedepth:6:.:.:0,6,62,6,62,62:.
        0|1:3,2,1:6:PASS:75:0|1:155415_T_G:75,0,120,84,126,210:155415   0|1:6,3,0:9:PASS:99:0|1:155415_T_A:108,0,243,126,252,378:155415 0/0:4,0,0:4:PASS:12:.:.:0,12,124,12,124,124:.   1|1:0,4,0:4:PASS:12:1|1:155415_T_A:180,12,0,180,12,180
:155415   0/0:13,0,0:13:PASS:36:.:.:0,36,540,36,540,540:. 0/0:18,0,0:18:PASS:54:.:.:0,54,752,54,752,752:. 0/0:15,0,0:15:PASS:36:.:.:0,36,540,36,540,540:. 0/0:13,0,0:13:PASS:36:.:.:0,36,540,36,540,540:. 0/0:27,0,0:27:PASS:39:.:.:0,39,1036,
39,1036,1036:.      ./.:3,0,0:3:genotypedepth:9:.:.:0,9,121,9,121,121:.     0/0:21,0,0:21:PASS:54:.:.:0,54,810,54,810,810:. 0/0:12,0,0:12:PASS:36:.:.:0,36,425,36,425,425:. 0/0:5,0,0:5:PASS:15:.:.:0,15,209,15,209,209:.   ./.:1,0,0:1:genoty
pedepth:3:.:.:0,3,42,3,42,42:.        ./.:3,0,0:3:genotypedepth:9:.:.:0,9,113,9,113,113:.     0/0:4,0,0:4:PASS:12:.:.:0,12,141,12,141,141:.   0/0:17,0,0:17:PASS:45:.:.:0,45,675,45,675,675:. 2|2:0,0,4:4:PASS:12:1|1:155311_C_T:180,180,180,1
2,12,0:155311   ./.:0,0,1:1:genotypedepth:3:.:.:45,45,45,3,3,0:.        ./.:3,0,0:3:genotypedepth:9:.:.:0,9,125,9,125,125:.     0/0:10,0,0:10:PASS:27:.:.:0,27,405,27,405,405:. 0/0:10,0,0:10:PASS:30:.:.:0,30,340,30,340,340:. 0/0:10,0,0:10:
PASS:30:.:.:0,30,323,30,323,323:. ./.:1,0,0:1:genotypedepth:3:.:.:0,3,25,3,25,25:.        1|1:0,4,0:4:PASS:12:1|1:155402_CAT_C:180,12,0,180,12,180:155402 0/0:18,0,0:18:PASS:51:.:.:0,51,765,51,765,765:. 0/0:11,0,0:11:PASS:33:.:.:0,33,418,3
3,418,418:. 0/0:11,0,0:11:PASS:30:.:.:0,30,450,30,450,450:. 0/0:7,0,0:7:PASS:21:.:.:0,21,262,21,262,262:.   0/0:4,0,0:4:PASS:12:.:.:0,12,140,12,140,140:.   0/0:9,0,0:9:PASS:0:.:.:0,0,209,0,209,209:.      0/0:10,0,0:10:PASS:30:.:.:0,30,414
,30,414,414:. 0/0:5,0,0:5:PASS:15:.:.:0,15,163,15,163,163:.   0/0:4,0,0:4:PASS:12:.:.:0,12,129,12,129,129:.   ./.:3,0,0:3:genotypedepth:9:.:.:0,9,113,9,113,113:.     0/0:11,0,0:11:PASS:33:.:.:0,33,387,33,387,387:. 0/0:7,0,0:7:PASS:21:.:.:
0,21,280,21,280,280:.   0/0:15,0,0:15:PASS:42:.:.:0,42,630,42,630,630:. 0/0:10,0,0:10:PASS:30:.:.:0,30,387,30,387,387:. ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    ./.:1,0,0:1:genotypedepth:3:.:.:0,3,15,3,15,15:.        ./.:3,0,0:3:genotypede
pth:6:.:.:0,6,90,6,90,90:.        0/0:11,0,0:11:PASS:33:.:.:0,33,413,33,413,413:. 0/0:5,0,0:5:PASS:15:.:.:0,15,197,15,197,197:.   0/0:6,0,0:6:PASS:18:.:.:0,18,224,18,224,224:.   ./.:9,0,0:9:PASS:.:.:.:0,0,0,0,0,0:.    0/0:12,0,0:12:PASS:3
6:.:.:0,36,489,36,489,489:. ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    0/0:26,0,0:26:PASS:72:.:.:0,72,1080,72,1080,1080:.      0/0:6,0,0:6:PASS:18:.:.:0,18,239,18,239,239:.
Scaffold_1028   155480  .       C       .       .       PASS    AN=90;DP=575    GT:DP:FT:RGQ    ./.:1:genotypedepth:3   ./.:3:genotypedepth:9   ./.:24:PASS:0   ./.:12:PASS:0   0/0:4:PASS:12   ./.:0:PASS:0    ./.:2:genotypedepth:6   0/0:14
:PASS:33  0/0:14:PASS:42  ./.:7:PASS:0    ./.:6:PASS:0    0/0:9:PASS:24   ./.:1:genotypedepth:3   0/0:21:PASS:63  ./.:2:genotypedepth:6   0/0:7:PASS:21   ./.:3:genotypedepth:9   0/0:5:PASS:15   0/0:9:PASS:27   0/0:4:PASS:12   0/0:4:PASS:1
2   0/0:12:PASS:36  0/0:19:PASS:54  0/0:14:PASS:42  0/0:12:PASS:33  0/0:31:PASS:93  0/0:4:PASS:6    0/0:19:PASS:48  0/0:13:PASS:39  0/0:5:PASS:15   ./.:1:genotypedepth:3   0/0:4:PASS:12   0/0:4:PASS:12   0/0:16:PASS:42  ./.:4:PASS:0    ./
.:1:genotypedepth:3   ./.:3:genotypedepth:9   0/0:11:PASS:33  0/0:11:PASS:33  0/0:10:PASS:30  ./.:1:genotypedepth:3   ./.:2:genotypedepth:6   0/0:21:PASS:60  0/0:13:PASS:33  0/0:12:PASS:36  0/0:8:PASS:21   0/0:5:PASS:15   0/0:10:PASS:14
0/0:12:PASS:36  0/0:5:PASS:15   0/0:4:PASS:12   0/0:4:PASS:12   0/0:11:PASS:27  0/0:7:PASS:21   0/0:17:PASS:35  0/0:12:PASS:30  ./.:0:PASS:0    ./.:2:genotypedepth:6   ./.:3:PASS:0    0/0:11:PASS:33  0/0:5:PASS:15   0/0:7:PASS:18   ./.:9:
PASS:0    0/0:13:PASS:39  ./.:2:genotypedepth:6   0/0:27:PASS:39  0/0:6:PASS:18
Scaffold_1028   155481  .       C       T,A     3288.21 PASS    AC=12,1;AF=0.115,0.009615;AN=104;BaseQRankSum=0;DP=582;ExcessHet=0;FS=4.835;InbreedingCoeff=0.4306;MLEAC=13,1;MLEAF=0.1,0.007692;MQ=32.56;MQRankSum=0;QD=23.5;ReadPosRankSum=0
;SOR=1.516        GT:AD:DP:FT:GQ:PGT:PID:PL:PS    ./.:1,0,0:1:genotypedepth:3:.:.:0,3,30,3,30,30:.        ./.:3,0,0:3:genotypedepth:9:.:.:0,9,125,9,125,125:.     1|1:0,28,0:28:PASS:84:1|1:155402_CAT_C:1260,84,0,1260,84,1260:155402    0/0:
12,0,0:12:PASS:0:.:.:0,0,301,0,301,301:.    0/0:4,0,0:4:PASS:12:.:.:0,12,129,12,129,129:.   ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    ./.:2,0,0:2:genotypedepth:6:.:.:0,6,80,6,80,80:.        0/0:14,0,0:14:PASS:33:.:.:0,33,495,33,495,495:. 0/
0:14,0,0:14:PASS:42:.:.:0,42,483,42,483,483:. 0/0:7,0,0:7:PASS:0:.:.:0,0,186,0,186,186:.      0/0:6,0,0:6:PASS:0:.:.:0,0,84,0,84,84:. 1|1:0,10,0:10:PASS:30:1|1:155402_CAT_C:450,30,0,450,30,450:155402       ./.:1,0,0:1:genotypedepth:3:.:.:
0,3,42,3,42,42:.        1|1:0,23,0:23:PASS:69:1|1:155402_CAT_C:1035,69,0,1035,69,1035:155402    ./.:2,0,0:2:genotypedepth:6:.:.:0,6,80,6,80,80:.        0/0:7,0,0:7:PASS:21:.:.:0,21,254,21,254,254:.   ./.:3,0,0:3:genotypedepth:9:.:.:0,9,10
0,9,100,100:.     0|1:3,2,1:6:PASS:75:0|1:155415_T_G:75,0,120,84,126,210:155415   0|1:6,3,0:9:PASS:99:0|1:155415_T_A:108,0,243,126,252,378:155415 0/0:4,0,0:4:PASS:12:.:.:0,12,124,12,124,124:.   1|1:0,4,0:4:PASS:12:1|1:155415_T_A:180,12,0,
180,12,180:155415   0/0:12,0,0:12:PASS:36:.:.:0,36,474,36,474,474:. 0/0:19,0,0:19:PASS:54:.:.:0,54,810,54,810,810:. 0/0:14,0,0:14:PASS:42:.:.:0,42,581,42,581,581:. 0/0:12,0,0:12:PASS:0:.:.:0,0,418,0,418,418:.    0/0:31,0,0:31:PASS:93:.:.:
0,93,1236,93,1236,1236:.      0/2:2,0,2:4:PASS:67:.:.:67,73,157,0,84,78:.     0/0:19,0,0:19:PASS:51:.:.:0,51,765,51,765,765:. 0/0:13,0,0:13:PASS:39:.:.:0,39,483,39,483,483:. 0/0:5,0,0:5:PASS:15:.:.:0,15,209,15,209,209:.   ./.:1,0,0:1:geno
typedepth:3:.:.:0,3,42,3,42,42:.        0/0:4,0,0:4:PASS:12:.:.:0,12,141,12,141,141:.   0/0:4,0,0:4:PASS:12:.:.:0,12,141,12,141,141:.   0/0:16,0,0:16:PASS:42:.:.:0,42,630,42,630,630:. 0/0:4,0,0:4:PASS:0:.:.:0,0,72,0,72,72:. ./.:1,0,0:1:ge
notypedepth:3:.:.:0,3,30,3,30,30:.        ./.:3,0,0:3:genotypedepth:9:.:.:0,9,125,9,125,125:.     0/0:11,0,0:11:PASS:33:.:.:0,33,417,33,417,417:. 0/0:9,0,0:9:PASS:27:.:.:0,27,347,27,347,347:.   0/0:10,0,0:10:PASS:30:.:.:0,30,323,30,323,32
3:. ./.:1,0,0:1:genotypedepth:3:.:.:0,3,25,3,25,25:.        1|1:0,5,0:5:PASS:15:1|1:155402_CAT_C:225,15,0,225,15,225:155402 0/0:21,0,0:21:PASS:60:.:.:0,60,873,60,873,873:. 0/0:13,0,0:13:PASS:33:.:.:0,33,495,33,495,495:. 0/0:13,0,0:13:PASS
:39:.:.:0,39,506,39,506,506:. 0/0:8,0,0:8:PASS:21:.:.:0,21,315,21,315,315:.   0/0:5,0,0:5:PASS:15:.:.:0,15,186,15,186,186:.   0/0:10,0,0:10:PASS:30:.:.:0,30,367,30,367,367:. 0/0:12,0,0:12:PASS:36:.:.:0,36,489,36,489,489:. 0/0:5,0,0:5:PASS
:15:.:.:0,15,163,15,163,163:.   0/0:4,0,0:4:PASS:12:.:.:0,12,129,12,129,129:.   0/0:4,0,0:4:PASS:12:.:.:0,12,141,12,141,141:.   0/0:11,0,0:11:PASS:27:.:.:0,27,405,27,405,405:. 0/0:7,0,0:7:PASS:21:.:.:0,21,266,21,266,266:.   0/0:17,0,0:17:
PASS:42:.:.:0,42,630,42,630,630:. 0/0:12,0,0:12:PASS:30:.:.:0,30,450,30,450,450:. ./.:0,0,0:0:PASS:.:.:.:0,0,0,0,0,0:.    ./.:2,0,0:2:genotypedepth:6:.:.:0,6,84,6,84,84:.        ./.:2,0,0:2:genotypedepth:3:.:.:0,3,45,3,45,45:.        0/0:
11,0,0:11:PASS:33:.:.:0,33,413,33,413,413:. 0/0:5,0,0:5:PASS:15:.:.:0,15,197,15,197,197:.   0/0:7,0,0:7:PASS:18:.:.:0,18,270,18,270,270:.   0/0:9,0,0:9:PASS:0:.:.:0,0,170,0,170,170:.      0/0:13,0,0:13:PASS:39:.:.:0,39,531,39,531,531:. ./
.:2,0,0:2:genotypedepth:6:.:.:0,6,76,6,76,76:.        0/0:25,0,0:25:PASS:75:.:.:0,75,976,75,976,976:. 0/0:6,0,0:6:PASS:18:.:.:0,18,239,18,239,239:

**Comment by edgardomortiz** [comment]
Great, thanks! I will try to fix it this afternoon

**Comment by giyany** [comment]
Thank you for your work!
I use this tool all the time, it's simple and very fast.

**Comment by edgardomortiz** [comment]
@Rahmmy @linsson @giyany the Issue is solved, please re-clone the repository (v2.8) and try again, `*` represent deletions and they should show in the matrix as `-`. I had introduced the bug in v2.7, when I re-wrote most of the code.

Edgardo
