### ISSUE TITLE
Coordinates of alignment sites

### ISSUE THREAD

**Issue by matthewglasenapp** [edgardomortiz/vcf2phylip#36]
Thank you for such a useful tool. Is it be possible to extract the coordinates for the sites included in the alignment?

**Comment by edgardomortiz** [comment]
It didn't before but it can now! Just re-clone the repository for version 2.7, you can add the option `-w` or `--write-used-sites` to your commands to create a tab-separated file of the coordinates of the used sites and the number of samples on each site.

Edgardo

**Comment by matthewglasenapp** [comment]
Incredible! Thanks so much! Worked perfectly.
