### ISSUE TITLE
UnboundLocalError: local variable 'used_sites' referenced before assignment

### ISSUE THREAD

**Issue by danielyao12** [edgardomortiz/vcf2phylip#37]
Hi Edgardo,

When I used the vcf2phylip.py to convert the vcf file of SNP to nexus format, I got the error message as follow.
```
Converting file 'dqgg_20210720.filtered.vcf':

Number of samples in VCF: 31
Traceback (most recent call last):
  File "./vcf2phylip.py", line 513, in <module>
    main()
  File "./vcf2phylip.py", line 340, in main
    used_sites.write(record[0] + "\t" + record[1] + "\t" + str(num_samples_locus) + "\n")
UnboundLocalError: local variable 'used_sites' referenced before assignment
```

The code I used was 
```
./vcf2phylip.py --input dqgg_20210720.filtered.vcf --phylip-disable --nexus --output-prefix 2ndconversion
```

The SNP in the vcf file was called using bcftools mpileup, and the vcf file has been indexed using bcftools index. Do you know how should I do to fix my problem?

Best,
Xin

**Comment by edgardomortiz** [comment]
My fault!, I introduced a bug with the latest function I added. Please re-clone and use your same command, it should work now.

Edgardo

**Comment by edgardomortiz** [comment]
Cool, thanks for letting me know it worked!

Closing the issue, please re-open if needed
