### ISSUE TITLE
Max character length for seq IDs

### ISSUE THREAD

**Issue by Neato-Nick** [edgardomortiz/vcf2phylip#38]
VCF allows unlimited character length for sequence IDs, but apparently[ PHYLIP allows only 10](http://www.phylo.org/tools/obsolete/phylip.html). Would there be a way to force unique character names if the input is longer than 10 characters? Or, at least provide a warning that the output will be invalid?

Also, I got my vcf from graphtyper and the tool is working well!

**Comment by edgardomortiz** [comment]
I think I will add a warning when the names won't adhere to the Strict PHYLIP standard, however most current phylogenetic tools support Relaxed PHYLIP with no problem.

Thanks for the info about `graphtyper`, I will add it to the `README` and link it to this Issue

**Comment by Neato-Nick** [comment]
Ah ok, that makes sense. I'm new to this format, I ran into issues using
SplitsTree
