### ISSUE TITLE
KeyError: '2'

### ISSUE THREAD

**Issue by matnguyen** [edgardomortiz/vcf2phylip#4]
I'm trying to run vcf2phylip on a VCF obtained from GATK's CombineVariants.

However, when trying to run it I get:

```
$ python ~/bin/vcf2phylip/vcf2phylip.py --input all_variants.vcf -f -p
    Traceback (most recent call last):
      File "/home/mnguyen/bin/vcf2phylip/vcf2phylip.py", line 387, in <module>
        main()
      File "/home/mnguyen/bin/vcf2phylip/vcf2phylip.py", line 212, in main
        site_tmp = ''.join([(amb[(nuc[broken[i][0]], nuc[broken[i][2]])]) for i in range(9, index_last_sample)])
    KeyError: '2'
```

**Comment by edgardomortiz** [comment]
Hi Matthew,

I would need a few thousand lines of your VCF to diagnose the problem. As far as I remember, GATK doesn't have a single VCF format as output.

You can get this fragment of your file with this:
`head -2000 all_variants,vcf > all_variants_2000.vcf`

**Comment by edgardomortiz** [comment]
Hi again, did you solve the issue?

**Comment by matnguyen** [comment]
Hello,

Correct, my genotypes are haploid.  I will pull and rerun to ensure everything works then close this issue

Thank you for the fix :)

**Comment by edgardomortiz** [comment]
I guess I will just close this issue
