### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by lyn320** [edgardomortiz/vcf2phylip#42]
my code is 
python vcf2phylip.py --input of_snp.vcf.gz  
and I got an error but don't know how to fix it, can you help me? thank you so much!

Traceback (most recent call last):
  File "vcf2phylip.py", line 23, in <module>
    from pathlib import Path
ImportError: No module named pathlib
tree_out.log (END)

**Comment by lyn320** [comment]
when I use python3, this error didn't show, so I think use python3 can be a solution.

**Comment by edgardomortiz** [comment]
Exactly, the script is for python3, I will add that to the README, thanks

Edgardo
