### ISSUE TITLE
SNPs that passed the filters: 0

### ISSUE THREAD

**Issue by Peijiawei2022** [edgardomortiz/vcf2phylip#45]
Hello,
        when I tried to convert VCF format(
[Uploading timetree_1.vcf.gz…]()
) to Phylip format using vcf2phylip, all the SNPs was not preserved. This data is 9 samples extracted from a complete VCF file, and the complete VCF file can be converted normally.

**Comment by edgardomortiz** [comment]
I'm afraid I need more info, how did you extract the 9 samples? can you share a few thousand lines of your9-sample VCF?

Edgardo

**Comment by Peijiawei2022** [comment]
vcftools --gzvcf barly_panseq_130_all.cds.maff.rename.snp.vcf.gz --keep simple.txt --recode --stdout | gzip -c > timetree_1.vcf.gz
![图片](https://github.com/edgardomortiz/vcf2phylip/assets/130423011/afe60cb5-1f8a-4b6b-8b0f-fc7f49318b2d)

**Comment by edgardomortiz** [comment]
The 9 SNPs you shared looked OK, perhaps the problem (if there is one) is further ahead in the file. Unfortunately I can't fix the problem if I don't have a piece of your VCF file (a few thousand lines are OK)

**Comment by Peijiawei2022** [comment]
will, just moment I use the latest v2.8, everything is OK. the problem occurs when i use the v2.0,thanks!

**Comment by edgardomortiz** [comment]
cool
