### ISSUE TITLE
unexpected token 'newline' error

### ISSUE THREAD

**Issue by faulk-lab** [edgardomortiz/vcf2phylip#48]
I'm having an issue converting a vcf created with pggb. It is in format ##fileformat=VCFv4.2
Any ideas?

```
vcf2phylip.py -i combined.fasta.a8a102b.7608fc1.afc7f52.smooth.final.Panubis1.1.vcf
/usr/local/bin/vcf2phylip.py: line 7: syntax error near unexpected token `newline'
/usr/local/bin/vcf2phylip.py: line 7: `<!DOCTYPE html>'
```

**Comment by edgardomortiz** [comment]
Hi @faulk-lab ,

It seems you downloaded the .py directly from your web browser (it was downloaded as a webpage). Unfortunately it is one of the quirks of GitHub, you need to clone the repository to download the correct Python format.

Here the instructions: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository


Edgardo

**Comment by faulk-lab** [comment]
Aha! that worked perfectly. Thank you!
