### ISSUE TITLE
KeyError: '2': always met this error when converting a vcf file to phylip file.

### ISSUE THREAD

**Issue by mxtu97** [edgardomortiz/vcf2phylip#49]
I have modified the variety names to be four digits, such as 4111, ensuring they are within 10 characters. However, I am still encountering this error. Could you please teach me how to resolve it?

$ python3 vcf2phylip-2.8/vcf2phylip.py -i test.vcf

Converting file 'test.vcf':

Number of samples in VCF: 290
Traceback (most recent call last):
  File "vcf2phylip-2.8/vcf2phylip.py", line 502, in <module>
    main()
  File "vcf2phylip-2.8/vcf2phylip.py", line 316, in main
    site_tmp = get_matrix_column(record, num_samples,
  File "vcf2phylip-2.8/vcf2phylip.py", line 129, in get_matrix_column
    column += AMBIG[geno_nuc]
KeyError: '2'

**Comment by edgardomortiz** [comment]
Hi @mxtu97 ,

I need more information, there is no "variety" field in the VCF format, what did you change in your VCF?. Anyway, the error is not related to that, I guess you have some malformed genotypes. If you can share a few thousand lines from your VCF I might be able to help...

Edgardo

**Comment by mxtu97** [comment]
Yeah, of course. This is the first few lines of the VCF file, and the variety names are not listed here completely.
##fileformat=VCFv4.2
##fileDate=20240320
##source=PLINKv1.90
##contig=<ID=1,length=37965022>
##contig=<ID=2,length=35942269>
##contig=<ID=3,length=44763783>
##contig=<ID=4,length=25659525>
##contig=<ID=5,length=45950378>
##contig=<ID=6,length=48703379>
##contig=<ID=7,length=32298698>
##contig=<ID=8,length=28328290>
##contig=<ID=9,length=65861953>
##contig=<ID=10,length=26591745>
##contig=<ID=11,length=57880206>
##contig=<ID=12,length=65292886>
##contig=<ID=13,length=79059969>
##contig=<ID=14,length=71178157>
##contig=<ID=15,length=59490990>
##contig=<ID=16,length=52509307>
##contig=<ID=17,length=60977511>
##contig=<ID=18,length=53650893>
##contig=<ID=19,length=68384616>
##INFO=<ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  R4157   R4158   R4163   R4168   R4171   R4176   R4177   R4179   R4180   R4181   R4182   R4187   R4191   R4194   R4199   R4202   R4210   R4213   R4215   R4218   R4219   R4220   R4222
1       65427   1_65427 2       1       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/1     0/0     0/0
1       110988  1_110988        2       1       .       .       PR      GT      0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/1     0/0     0/0     0/0     0/0     0/1     0/0     1/1     0/0     1/1     0/0     0/0     0/0     0/0     0/0
1       124600  1_124600        2       1       .       .       PR      GT      0/0     0/0     0/0     1/1     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/1     0/0
1       124713  1_124713        2       1       .       .       PR      GT      0/0     0/0     0/1     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/1     0/0     0/0     0/0     0/1     0/0
1       124751  1_124751        2       1       .       .       PR      GT      0/0     0/0     0/1     1/1     0/1     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/0     0/0     0/1     1/1     0/0     0/0     0/1     1/1     1/1
1       124781  1_124781        2       1       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/1     0/0
1       124787  1_124787        2       1       .       .       PR      GT      0/0     0/0     0/1     1/1     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/1     0/0
1       125023  1_125023        2       1       .       .       PR      GT      0/0     0/0     1/1     1/1     0/1     0/0     0/0     0/0     0/1     1/1     0/0     0/0     0/0     0/0     0/0     0/0     1/1     0/0     0/0     0/1     1/1     0/0

**Comment by edgardomortiz** [comment]
As I suspected your genotypes have a non-standard format, fields 3 and 4 (REF and ALT) must be nucleotides and not numbers, see here:

https://en.m.wikipedia.org/wiki/File:Binary_BCF_versus_VCF_format.png

Interesting, how did you generate this VCF?


Edgardo

**Comment by mxtu97** [comment]
The problem was solved, indeed because of the problem of genotypes. Thank.

**Comment by edgardomortiz** [comment]
Great, don't hesitate to ask if you find a new issue...

Edgardo
