### ISSUE TITLE
Using with Phylip

### ISSUE THREAD

**Issue by mayasheth** [edgardomortiz/vcf2phylip#6]
Hi- what Phylip programs does this produce inputs for? I tried using the file with the Neighbor program and got an error that the input was of the wrong type.

Thanks!

**Comment by edgardomortiz** [comment]
Hello @mayasheth ,
In the README (https://github.com/edgardomortiz/vcf2phylip) I detail the output formats you can get. Honestly I never worked with the package PHYLIP, although I imagine they created the PHYLIP format (which is now used by many other phylogenetic programs).
Reading the documentation of Phylip (http://evolution.genetics.washington.edu/phylip/doc/main.html#inputfiles) it says the format my script produces is correct however there is a limitation for the strict Phylip format, the names of the samples must be at most 10 characters long, you can try renaming your samples and running my script again. I could make my script to truncate the names to 10 characters but this may create non-unique names.

Let me know if this works. 

Edgardo

**Comment by edgardomortiz** [comment]
Please re-open the issue if problem persists, closing this now.
