### ISSUE TITLE
Getting an error on vcf2phylip

### ISSUE THREAD

**Issue by NLRivera1** [edgardomortiz/vcf2phylip#7]
Hello, 
 I'm having issues converting my vcf file. I work with Ubuntu. 

The command I entered: python ~/vcf2phylip/vcf2phylip.py -i Final.vcf 
Traceback (most recent call last):
  File "/home/computer/vcf2phylip/vcf2phylip.py", line 397, in <module>
    main()
  File "/home/computer/vcf2phylip/vcf2phylip.py", line 220, in main
    site_tmp = ''.join([(amb[(nuc[broken[i][0]], nuc[broken[i][2]])]) for i in range(9, index_last_sample)])
KeyError: '2'

I've attached the file here as well.
[Final.vcf.gz](https://github.com/edgardomortiz/vcf2phylip/files/2652920/Final.vcf.gz)

Any and all help is appreciated!

**Comment by edgardomortiz** [comment]
Hello, please clone again, retry, and let me know if it works. It should be fixed, I tested it with the provided matrix.

Edgardo

**Comment by edgardomortiz** [comment]
I will assume the issue was resolved and close it.

Edgardo
