### ISSUE TITLE
error with using python 3

### ISSUE THREAD

**Issue by yimingweng** [edgardomortiz/vcf2phylip#8]
Hi, 

Thank you for providing the useful tools. However, I got error of "invalid syntax" on line 197. I think it's because I'm using python 3 so "**print**" becomes a function. I tried `print()` instead of `print ` and it worked.
thank you.  

YiMing

**Comment by edgardomortiz** [comment]
Thanks!, I replaced all `print` by `print()`, I gues the script is now compatible with python3

Edgardo
